#!/usr/bin/env python3
"""
Bootstrap a generic hockey highlight Shared Drive layout.

Creates the canonical folder tree for a program/season and optionally writes
local env files containing both the new generic variables and legacy aliases.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from drive_config import (  # noqa: E402
    build_bootstrap_env,
    build_program_drive_layout,
    iter_layout_paths,
    normalize_drive_id,
    program_env_metadata,
)


def _parse_program_path(program_path: str) -> Tuple[str, str, str, str]:
    parts = [segment.strip() for segment in str(program_path or "").split("/") if segment.strip()]
    if len(parts) < 4:
        raise ValueError("program path must look like Programs/<league>/<team>/<season>")
    root_folder = "/".join(parts[:-3])
    league, team, season = parts[-3:]
    return root_folder, league, team, season


def _get_drive_service(creds_path: Path):
    from googleapiclient.discovery import build
    from google.oauth2 import service_account

    credentials = service_account.Credentials.from_service_account_file(
        str(creds_path),
        scopes=["https://www.googleapis.com/auth/drive"],
    )
    return build("drive", "v3", credentials=credentials)


def _parse_env_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _render_env_payload(payload: Dict[str, str]) -> str:
    lines = ["# Generated by scripts/setup_highlight_drive.py"]
    for key in sorted(payload):
        value = str(payload[key]).replace("\n", " ").strip()
        lines.append(f'{key}="{value}"')
    lines.append("")
    return "\n".join(lines)


def _list_child_folders(service, *, parent_id: str, drive_id: str) -> list[dict[str, Any]]:
    params: Dict[str, Any] = {
        "q": (
            f"'{parent_id}' in parents and trashed=false and "
            "mimeType='application/vnd.google-apps.folder'"
        ),
        "fields": "files(id,name)",
        "pageSize": 1000,
        "supportsAllDrives": True,
        "includeItemsFromAllDrives": True,
    }
    if drive_id:
        params["corpora"] = "drive"
        params["driveId"] = drive_id
    result = service.files().list(**params).execute()
    return list(result.get("files", []) or [])


def _find_child_folder(service, *, parent_id: str, name: str, drive_id: str) -> str:
    target = str(name or "").strip()
    if not target:
        return ""
    for item in _list_child_folders(service, parent_id=parent_id, drive_id=drive_id):
        if str(item.get("name") or "").strip().lower() == target.lower():
            return str(item.get("id") or "")
    return ""


def _ensure_child_folder(
    service,
    *,
    parent_id: str,
    name: str,
    drive_id: str,
    dry_run: bool,
) -> Tuple[str, bool]:
    if dry_run:
        return f"dryrun::{parent_id}/{name}", True
    existing = _find_child_folder(service, parent_id=parent_id, name=name, drive_id=drive_id)
    if existing:
        return existing, False
    created = (
        service.files()
        .create(
            body={
                "name": name,
                "mimeType": "application/vnd.google-apps.folder",
                "parents": [parent_id],
            },
            fields="id",
            supportsAllDrives=True,
        )
        .execute()
    )
    return str(created["id"]), True


def _ensure_folder_path(
    service: Optional[Any],
    *,
    drive_id: str,
    folder_path: str,
    dry_run: bool,
) -> Tuple[str, bool]:
    current_parent = drive_id or "root"
    created_any = False
    for segment in [part for part in str(folder_path or "").strip("/").split("/") if part]:
        current_parent, created = _ensure_child_folder(
            service,
            parent_id=current_parent,
            name=segment,
            drive_id=drive_id,
            dry_run=dry_run,
        )
        created_any = created_any or created
    return current_parent, created_any


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap the canonical hockey highlight Shared Drive layout.")
    parser.add_argument("--drive-id", required=True, help="Shared Drive ID or URL")
    parser.add_argument("--creds-path", type=Path, required=True, help="Service-account JSON path")
    parser.add_argument("--program-manifest", type=Path, default=None, help="Optional JSON program manifest to prefill league/team/season/layout")
    parser.add_argument("--program-path", default="", help="Program path like Programs/MHL/Amherst Ramblers/2025-26")
    parser.add_argument("--league", default="MHL", help="League name when --program-path is not provided")
    parser.add_argument("--team", default="Amherst Ramblers", help="Team/program name when --program-path is not provided")
    parser.add_argument("--season", default="2025-26", help="Season label when --program-path is not provided")
    parser.add_argument("--root-folder", default="Programs", help="Top-level folder name for program trees")
    parser.add_argument("--write-env", action="append", default=[], help="Write generated env vars to this file. Repeat as needed.")
    parser.add_argument("--write-manifest", type=Path, default=None, help="Write the bootstrap manifest JSON to this path")
    parser.add_argument("--dry-run", action="store_true", help="Print the manifest without creating Drive folders")
    parser.add_argument("--print-manifest", action="store_true", help="Print the manifest JSON to stdout")
    parser.add_argument("--no-legacy-aliases", action="store_true", help="Omit legacy env aliases from generated env files")
    args = parser.parse_args()

    drive_id = normalize_drive_id(args.drive_id)
    creds_path = args.creds_path.expanduser().resolve()
    if not creds_path.exists():
        raise FileNotFoundError(f"Credentials file not found: {creds_path}")

    manifest_data: Dict[str, Any] = {}
    if args.program_manifest:
        manifest_path = args.program_manifest.expanduser().resolve()
        manifest_data = json.loads(manifest_path.read_text(encoding="utf-8"))

    if args.program_path:
        root_folder, league, team, season = _parse_program_path(args.program_path)
    else:
        drive_layout = manifest_data.get("drive_layout") if isinstance(manifest_data.get("drive_layout"), dict) else {}
        root_folder = str(drive_layout.get("root_folder") or args.root_folder or "Programs").strip().strip("/") or "Programs"
        league = str(manifest_data.get("league") or args.league or "").strip()
        team = str(manifest_data.get("team") or args.team or "").strip()
        season = str(manifest_data.get("season") or args.season or "").strip()

    layout = build_program_drive_layout(
        league=league,
        team=team,
        season=season,
        root_folder=root_folder,
    )

    service = None
    drive_name = ""
    if not args.dry_run:
        service = _get_drive_service(creds_path)
        drive_meta = service.drives().get(driveId=drive_id).execute()
        drive_name = str(drive_meta.get("name") or "")

    folder_ids: Dict[str, str] = {}
    created_paths: list[str] = []
    for key, folder_path in iter_layout_paths(layout):
        folder_id, created = _ensure_folder_path(
            service,
            drive_id=drive_id,
            folder_path=folder_path,
            dry_run=bool(args.dry_run),
        )
        folder_ids[key] = folder_id
        if created:
            created_paths.append(folder_path)

    resolved = build_bootstrap_env(
        layout=layout,
        folder_ids=folder_ids,
        drive_id=drive_id,
        credentials_path=str(creds_path),
    )
    env_extra = program_env_metadata(league=league, team=team, season=season, layout=layout)
    manifest = {
        "drive": {
            "id": drive_id,
            "name": drive_name,
            "credentials_path": str(creds_path),
        },
        "program": {
            "program_id": manifest_data.get("program_id"),
            "league": league,
            "team": team,
            "season": season,
            "root_folder": root_folder,
        },
        "layout": layout.to_dict(),
        "folder_ids": folder_ids,
        "created_paths": created_paths,
        "env": resolved.to_env_dict(include_legacy=not bool(args.no_legacy_aliases)),
        "env_extra": env_extra,
        "dry_run": bool(args.dry_run),
    }

    for env_target in args.write_env:
        target_path = Path(env_target).expanduser().resolve()
        target_path.parent.mkdir(parents=True, exist_ok=True)
        payload = _parse_env_file(target_path)
        payload.update(resolved.to_env_dict(include_legacy=not bool(args.no_legacy_aliases)))
        payload.update(env_extra)
        target_path.write_text(_render_env_payload(payload), encoding="utf-8")

    if args.write_manifest:
        manifest_path = args.write_manifest.expanduser().resolve()
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    if args.print_manifest or not args.write_manifest:
        print(json.dumps(manifest, indent=2, sort_keys=True))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
